Finish stylized text prototype
WeijiaMa/CodeU-Spring-2018 pull request #3
Opened 2018-05-23 06:01 UTC by WeijiaMa

2018-05-23 22:08 UTC, dgalbraith33 requested changes

2018-05-23 22:08 UTC, dgalbraith33 commented on src/main/java/codeu/controller/ChatServlet.java
> +    String cleanedMessageContent = Jsoup.clean(messageContent, Whitelist.basic());
nit: Can you elaborate in this comment about what HTML is whitelisted?

2018-05-23 22:08 UTC, dgalbraith33 commented on src/test/java/codeu/controller/ChatServletTest.java
> +        "Contains \n<b>html</b> and  content.", messageArgumentCaptor.getValue().getContent());
Why the '\n' newline in this assert?

2018-05-28 15:06 UTC, tiffanycwong requested changes

2018-05-28 15:06 UTC, tiffanycwong commented on src/test/java/codeu/controller/ChatServletTest.java
> +        "Contains \n<b>html</b> and  content.", messageArgumentCaptor.getValue().getContent());
+1

2018-05-28 15:06 UTC, tiffanycwong commented on src/test/java/codeu/controller/ChatServletTest.java
> +
nit: remove this extra line

2018-05-28 15:06 UTC, tiffanycwong approved these changes

2018-05-28 15:07 UTC, tiffanycwong requested changes

2018-05-28 15:07 UTC, tiffanycwong commented on src/test/java/codeu/controller/ChatServletTest.java
> +
oops. connecting on this because i messed up with github :P

2018-05-29 04:35 UTC, WeijiaMa commented
I have updated with the changes @dgalbraith33 @tiffanycwong

2018-05-30 01:03 UTC, tiffanycwong approved these changes

2018-05-30 01:03 UTC, tiffanycwong commented
Please add description up top!

2018-05-30 01:51 UTC, merged